### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jstock78** [SteveBarnegren/CCLabelBMFontAnimated#3]
I'd like to include these effects in my project, but I don't see a license.  Could you update the GitHub project with a license so we can understand if we're allowed to use the code?

**Comment by SteveBarnegren** [comment]
Done! I've added the license to the readme and the top of the source files. You are more than welcome to use the code in your projects, including commercial, without attribution.

I did update the class for the most recent version of Cocos2d-x a while back, but there have been a couple of point releases since then.  I'm not working on any Cocos2d-x projects at the moment, so if you find anything that needs updated for the latest version and make any changes, then it would be great if you could send me a pull request. Thanks!

**Comment by jstock78** [comment]
Wow, that was fast, thank you!  I'll be sure to create pull requests for anything I find.
